=== ChristianMurphy/CoursesPortlet/courses-portlet-api/src/main/resources/xsd/generic/course-summary.xsd
<!--

    Licensed to Jasig under one or more contributor license
    agreements. See the NOTICE file distributed with this work
    for additional information regarding copyright ownership.
    Jasig licenses this file to you under the Apache License,
    Version 2.0 (the "License"); you may not use this file
    except in compliance with the License. You may obtain a
    copy of the License at:

    http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing,
    software distributed under the License is distributed on
    an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
    KIND, either express or implied. See the License for the
    specific language governing permissions and limitations
    under the License.

-->

<xs:schema xmlns="https://source.jasig.org/schemas/portlet/courses/course-summary"
    targetNamespace="https://source.jasig.org/schemas/portlet/courses/course-summary"
    xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.0">
    
    <xs:element name="course-term-summary">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="term-summary" type="term-summary">
                    <!-- Enforce terms having unique codes -->
                    <xs:unique name="unique_term_by_code">
                        <xs:selector xpath="term"/>
                        <xs:field xpath="code"/>
                    </xs:unique>
                </xs:element>
                <xs:element name="course-summary" type="course-summary" minOccurs="0" maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>
        <!-- Enforce course-summary having unique term_codes -->
        <xs:unique name="unique_course-summary_by_term-code">
            <xs:selector xpath="*/course-summary"/>
            <xs:field xpath="term_code"/>
        </xs:unique>
    </xs:element>
    
    <xs:complexType name="term-summary">
        <xs:sequence>
            <xs:element name="term" type="term" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="course-summary">
        <xs:sequence>
            <xs:element name="term_code" type="xs:string"/>
            <xs:element name="gpa" type="xs:double" minOccurs="0"/>
            <xs:element name="credits" type="xs:double" minOccurs="0"/>
            <xs:element name="course" type="course" minOccurs="0" maxOccurs="unbounded">
                <!-- Enforce course-summary/course having unique code within the term -->
                <xs:unique name="unique_course-summary_course_by_term-code">
                    <xs:selector xpath="."/>
                    <xs:field xpath="code"/>
                </xs:unique>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="term">
        <xs:sequence>
            <xs:element name="displayName" type="xs:string"/>
            <xs:element name="code" type="xs:string" minOccurs="0"/>
            <xs:element name="year" type="xs:integer" minOccurs="0"/>
            <xs:element name="termType" type="xs:string" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute name="current" type="xs:boolean" default="false"/>
    </xs:complexType>

    <xs:complexType name="course">
        <xs:sequence>
            <xs:element name="title" type="xs:string"/>
            <xs:element name="code" type="xs:string"/>
            <xs:element name="school" type="xs:string" minOccurs="0"/>
            <xs:element name="location" type="location" minOccurs="0"/>
            <xs:element name="meetingTimes" type="xs:string" minOccurs="0"/>
            <xs:element name="url" type="xs:string"/>
            <xs:element name="instructor" type="instructor" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="grade" type="xs:string" minOccurs="0"/>
            <xs:element name="credits" type="xs:double" minOccurs="0"/>
            <xs:element name="course-update" type="course-update" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="instructor">
        <xs:sequence>
            <xs:element name="abbreviation" type="xs:string"/>
            <xs:element name="fullName" type="xs:string"/>
            <xs:element name="identifier" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="location">
            <xs:sequence>
                <xs:element name="displayName" type="xs:string"/>
                <xs:element name="identifier" type="xs:string"/>
            </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="course-update">
            <xs:sequence>
                <xs:element name="title" type="xs:string"/>
                <xs:element name="description" type="xs:string"/>
                <xs:element name="url" type="xs:string"/>
            </xs:sequence>
            <xs:attribute name="newUpdate" type="xs:boolean"/>
            <xs:attribute name="type" type="xs:string"/>
    </xs:complexType>
    
</xs:schema>

=== ChristianMurphy/CoursesPortlet/courses-portlet-webapp/src/main/resources/mock-data/mock-course-summary.xml
<!--

    Licensed to Jasig under one or more contributor license
    agreements. See the NOTICE file distributed with this work
    for additional information regarding copyright ownership.
    Jasig licenses this file to you under the Apache License,
    Version 2.0 (the "License"); you may not use this file
    except in compliance with the License. You may obtain a
    copy of the License at:

    http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing,
    software distributed under the License is distributed on
    an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
    KIND, either express or implied. See the License for the
    specific language governing permissions and limitations
    under the License.

-->
<course-summary
    xmlns="https://source.jasig.org/schemas/portlet/courses/course-summary"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="https://source.jasig.org/schemas/portlet/courses/course-summary ../../../../../courses-portlet-api/src/main/resources/xsd/generic/course-summary.xsd">

    <gpa>3.25</gpa>
    <credits>40</credits>

    <term>
        <displayName>Winter 2012</displayName>
        <code>2012w</code>
        <gpa>3.0</gpa>
        <credits>20</credits>
    </term>

    <term current="true">
        <displayName>Spring 2012</displayName>
        <code>2012s</code>
        <gpa>3.5</gpa>
        <credits>20</credits>
    
        <course>
            <title>Design Awareness</title>
            <code>DSC 101</code>
            <school>School of Design</school>
            <location>
                <displayName>SSS 114</displayName>
                <identifier>SSS</identifier>
            </location>
            <meetingTimes>M-W-F, 1:30-2:30pm</meetingTimes>
            <url>http://courses.university.edu/dsc101/s11</url>
            <instructor>
                <abbreviation>Faculty</abbreviation>
                <fullName>Joe Faculty, Phd</fullName>
                <identifier>faculty</identifier>
            </instructor>
            <grade>A</grade>
            <credits>4</credits>
            <course-update newUpdate="true" type="announcement">
                <title>Guest Lecture Thursday</title>
                <description>
                Don't miss Thursday's guest lecture by Alan Cooper
            </description>
                <url>http://courses.university.edu/dsc101/s11/announcements/1.html</url>
            </course-update>
        </course>

        <course>
            <title>Drawing for Industry</title>
            <code>IND 120</code>
            <school>School of Design</school>
            <location>
                <displayName>LC 101</displayName>
                <identifier>LC</identifier>
            </location>
            <meetingTimes>M-W-F, 1:30-2:30pm</meetingTimes>
            <url>http://courses.university.edu/dsc101/s11</url>
            <instructor>
                <abbreviation>Staff</abbreviation>
                <fullName>Sam Staff</fullName>
                <identifier>staff</identifier>
            </instructor>
            <grade>A</grade>
            <credits>4</credits>
            <course-update newUpdate="false" type="announcement">
                <title>Guest Lecture Thursday</title>
                <description>
                Don't miss Thursday's guest lecture by Alan Cooper
            </description>
                <url>http://courses.university.edu/dsc101/s11/announcements/1.html</url>
            </course-update>
        </course>

        <course>
            <title>First-Year Composition</title>
            <code>ENG 101</code>
            <school>School of Design</school>
            <location>
                <displayName>SCL 115</displayName>
                <identifier>SCL</identifier>
            </location>
            <meetingTimes>M-W-F, 1:30-2:30pm</meetingTimes>
            <url>http://courses.university.edu/dsc101/s11</url>
            <instructor>
                <abbreviation>Faculty</abbreviation>
                <fullName>Joe Faculty, Phd</fullName>
                <identifier>faculty</identifier>
            </instructor>
            <grade>A</grade>
            <credits>4</credits>
        </course>

        <course>
            <title>Precalculus</title>
            <code>MAT 170</code>
            <school>School of Design</school>
            <location>
                <displayName>Becton 101</displayName>
                <identifier>BCT</identifier>
            </location>
            <meetingTimes>M-W-F, 1:30-2:30pm</meetingTimes>
            <url>http://courses.university.edu/dsc101/s11</url>
            <instructor>
                <abbreviation>Faculty</abbreviation>
                <fullName>Joe Faculty, Phd</fullName>
                <identifier>faculty</identifier>
            </instructor>
            <grade>C</grade>
            <credits>4</credits>
        </course>

        <course>
            <title>Graphic Design History</title>
            <code>GRA 111</code>
            <school>School of Design</school>
            <location>
                <displayName>WLH 205</displayName>
                <identifier>WLH</identifier>
            </location>
            <meetingTimes>M-W-F, 1:30-2:30pm</meetingTimes>
            <url>http://courses.university.edu/dsc101/s11</url>
            <instructor>
                <abbreviation>Faculty</abbreviation>
                <fullName>Joe Faculty, Phd</fullName>
                <identifier>faculty</identifier>
            </instructor>
            <grade>A</grade>
            <credits>4</credits>
        </course>

    </term>

</course-summary>
